fix after autotest subset 0

diff --git a/girt-add b/girt-add
--- a/girt-add
+++ b/girt-add
@@ -1,33 +1,34 @@
 #!/bin/dash
 if test $# -eq 0 ; then
     echo "usage: $0 <filenames>"
+    exit 1
 fi
 # check current location
-if ! test -e ".girt"; then
-    echo "fatal: this operation must be run in a work tree" >&2
+if ! test -e "$PWD/.girt"; then
+    echo "$0: error: girt repository directory .girt not found" >&2
     exit 1
 fi
 for file in $@; do
-    if ! test -e "$file";then
-        echo "error: $file does not exist" >&2
+    if ! test -e "$PWD/$file";then
+        echo "$0: error: can not open '$1'" >&2
         continue
     fi
-    gzip -c -n "$file" > .girt/tmp/compressed_tmp
-    hashed=$(cat .girt/tmp/compressed_tmp|sha1sum|cut -d' ' -f1)
+    gzip -c -n "$PWD/$file" > $PWD/.girt/tmp/compressed_tmp
+    hashed=$(cat $PWD/.girt/tmp/compressed_tmp|sha1sum|cut -d' ' -f1)
     dir=$(echo "$hashed" | cut -c1-2) # 2 char
     name=$(echo "$hashed" | cut -c3-40)
 
-    if ! test -e ".girt/objects/blob/$dir"; then
-        mkdir -p ".girt/objects/blob/$dir"
+    if ! test -e "$PWD/.girt/objects/blob/$dir"; then
+        mkdir -p "$PWD/.girt/objects/blob/$dir"
     fi
-    mv .girt/tmp/compressed_tmp .girt/objects/blob/$dir/$name
+    mv $PWD/.girt/tmp/compressed_tmp $PWD/.girt/objects/blob/$dir/$name
     
     # remove old one
     while read -r LINE; do
         filename=$(echo "$LINE" | cut -f2)
         if [ $filename = $file ] ; then
-            sed -i "/$LINE/d" '.girt/index'
+            sed -i "/$LINE/d" "$PWD/.girt/index"
         fi
-    done < .girt/index
-    printf "$hashed\t$file\n" >> .girt/index
+    done < "$PWD/.girt/index"
+    printf "$hashed\t$file\n" >> $PWD/.girt/index
 done
diff --git a/girt-commit b/girt-commit
--- a/girt-commit
+++ b/girt-commit
@@ -1,8 +1,8 @@
 #!/bin/dash
 
 # check current location
-if ! test -e ".girt"; then
-    echo "fatal: this operation must be run in a work tree" >&2
+if ! test -e "$PWD/.girt"; then
+    echo "$0: error: girt repository directory .girt not found" >&2
     exit 1
 fi
 
@@ -31,30 +31,30 @@ fi
 
 if $all; then
     # all files option
-    # save all files in index to `.girt/objects` and update index
+    # save all files in index to `$PWD/.girt/objects` and update index
     while read LINE; do
         file=$(echo "$LINE" | cut -f2)
-        gzip -c -n "$file" > .girt/tmp/compressed_tmp
-        hashed=$(cat .girt/tmp/compressed_tmp|sha1sum|cut -d' ' -f1)
+        gzip -c -n "$file" > $PWD/.girt/tmp/compressed_tmp
+        hashed=$(cat $PWD/.girt/tmp/compressed_tmp|sha1sum|cut -d' ' -f1)
         dir=$(echo "$hashed" | cut -c1-2) # 2 char
         name=$(echo "$hashed" | cut -c3-40)
 
-        if ! test -e ".girt/objects/blob/$dir"; then
-            mkdir -p ".girt/objects/blob/$dir"
+        if ! test -e "$PWD/.girt/objects/blob/$dir"; then
+            mkdir -p "$PWD/.girt/objects/blob/$dir"
         fi
-        mv .girt/tmp/compressed_tmp .girt/objects/blob/$dir/$name
-        printf "$hashed\t$file\n" >> .girt/tmp/index.tmp
-    done < .girt/index
-    mv .girt/tmp/index.tmp .girt/index
+        mv $PWD/.girt/tmp/compressed_tmp $PWD/.girt/objects/blob/$dir/$name
+        printf "$hashed\t$file\n" >> $PWD/.girt/tmp/index.tmp
+    done < $PWD/.girt/index
+    mv $PWD/.girt/tmp/index.tmp $PWD/.girt/index
 fi
 
-commit_number=$(tail -n1 .girt/commits | cut -f1)
+commit_number=$(tail -n1 $PWD/.girt/commits | cut -f1)
 if test -z $commit_number; then
     commit_number=-1
 fi
 commit_number=$((commit_number+1))
-cp .girt/index .girt/objects/commit/$commit_number
+cp $PWD/.girt/index $PWD/.girt/objects/commit/$commit_number
 
-printf '%d\t%s\n' "$commit_number" "$message" >> .girt/commits
+printf '%d\t%s\n' "$commit_number" "$message" >> $PWD/.girt/commits
 
-echo "Commited as commit $commit_number"
+echo "Committed as commit $commit_number"
diff --git a/girt-log b/girt-log
--- a/girt-log
+++ b/girt-log
@@ -1,7 +1,7 @@
 #!/bin/dash
-if ! test -e ".girt"; then
-    echo "fatal: this operation must be run in a work tree" >&2
+if ! test -e "$PWD/.girt"; then
+    echo "$0: error: girt repository directory .girt not found" >&2
     exit 1
 fi
 
-cat .girt/commits | sort -r -n
+cat $PWD/.girt/commits | sort -r -n | sed 's/\t/ /g'
diff --git a/girt-show b/girt-show
--- a/girt-show
+++ b/girt-show
@@ -1,9 +1,8 @@
 #!/bin/dash
-if ! test -e ".girt"; then
-    echo "fatal: this operation must be run in a work tree" >&2
+if ! test -e "$PWD/.girt"; then
+    echo "$0: error: girt repository directory .girt not found" >&2
     exit 1
 fi
-
 usage() { echo "usage: $0 [commit]:filename" 1>&2; exit 1; }
 
 commit=$(echo "$1"|cut -d':' -f1)
@@ -17,10 +16,10 @@ load_commit(){
         dir=$(echo "$hashed" | cut -c1-2) # 2 char
         name=$(echo "$hashed" | cut -c3-40)
 
-        if (! test -z $dir) && (! test -z name); then
-            gunzip -c -n .girt/objects/blob/$dir/$name
+        if (! test -z $dir) && (! test -z $name); then
+            gunzip -c -n "$PWD/.girt/objects/blob/$dir/$name"
         fi
-    done < ".girt/objects/commit/$1"
+    done < "$PWD/.girt/objects/commit/$1"
 }
 
 if ! test -z "$commit"; then
@@ -28,7 +27,15 @@ if ! test -z "$commit"; then
     exit 0
 fi
 
-for file in .girt/objects/commit/*; do
-    basename=$(basename $file)
-    load_commit $basename $filename
-done
+while read -r LINE; do
+    file=$(echo "$LINE" | cut -f2)
+    if [ "$file" != "$filename" ]; then continue 
+    fi
+    dir=$(echo "$LINE" | cut -c1-2) # 2 char
+    name=$(echo "$LINE" | cut -c3-40)
+
+    if (! test -z $dir) && (! test -z $name); then
+        gunzip -c -n "$PWD/.girt/objects/blob/$dir/$name"
+    fi
+    exit 0
+done < $PWD/.girt/index
